---
- name: "2.1 - 2.18 - Configure Docker daemon settings via template"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: "2.15 - Create docker.service.d directory"
  block:
    - name: Ensure directory exists
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

- name: "2.16 - Configure TLS authentication for Docker daemon"
  block:
    - name: Ensure TLS is configured
      command: docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem version
      changed_when: false
      ignore_errors: true
      register: tls_check

    - name: Warn if TLS not configured
      debug:
        msg: "WARNING: TLS authentication not configured for Docker daemon (CIS 2.16)"
      when: tls_check.rc != 0

- name: "2.17 - Configure default ulimits in systemd"
  block:
    - name: Configure systemd ulimits
      blockinfile:
        path: /etc/systemd/system/docker.service.d/limits.conf
        create: yes
        block: |
          [Service]
          LimitNOFILE=1024
          LimitNPROC=1024
      notify: restart docker

# Handler for docker service
- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes