---
- name: restart docker
  service:
    name: docker
    state: restarted

- name: reload docker
  service:
    name: docker
    state: reloaded

- name: restart auditd
  service:
    name: auditd
    state: restarted